"""Static site generator for feed index page."""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml
from pydantic import BaseModel

from linkfeed.models import Feed

logger = logging.getLogger(__name__)


class SiteConfig(BaseModel):
    """Configuration for site index page."""
    
    title: str = "Feed Index"
    description: str = "A collection of RSS and JSON feeds"


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #ffffff;
            --text: #1a1a1a;
            --muted: #666666;
            --border: #e5e5e5;
            --accent: #0066cc;
        }}
        @media (prefers-color-scheme: dark) {{
            :root {{
                --bg: #1a1a1a;
                --text: #e5e5e5;
                --muted: #999999;
                --border: #333333;
                --accent: #66b3ff;
            }}
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
            max-width: 800px;
            margin: 0 auto;
        }}
        h1 {{ margin-bottom: 0.5rem; }}
        .subtitle {{ color: var(--muted); margin-bottom: 2rem; }}
        .feed-list {{ list-style: none; }}
        .feed-item {{
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1rem;
        }}
        .feed-title {{
            font-size: 1.25rem;
            margin-bottom: 0.5rem;
        }}
        .feed-title a {{
            color: var(--accent);
            text-decoration: none;
        }}
        .feed-title a:hover {{ text-decoration: underline; }}
        .feed-desc {{ color: var(--muted); margin-bottom: 0.75rem; }}
        .feed-meta {{
            font-size: 0.875rem;
            color: var(--muted);
        }}
        .feed-links {{
            margin-top: 0.75rem;
            font-size: 0.875rem;
        }}
        .feed-links a {{
            color: var(--accent);
            margin-right: 1rem;
        }}
        footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
            color: var(--muted);
            font-size: 0.875rem;
        }}
    </style>
    {autodiscovery}
</head>
<body>
    <h1>{title}</h1>
    <p class="subtitle">{description}</p>
    
    <ul class="feed-list">
        {feed_items}
    </ul>
    
    <footer>
        <p>Generated by <a href="https://github.com/linkfeed/linkfeed">linkfeed</a> on {generated_at}</p>
    </footer>
</body>
</html>
"""

FEED_ITEM_TEMPLATE = """
<li class="feed-item">
    <h2 class="feed-title"><a href="{json_url}">{title}</a></h2>
    <p class="feed-desc">{description}</p>
    <p class="feed-meta">{item_count} items · Last updated: {last_updated}</p>
    <div class="feed-links">
        <a href="{json_url}">JSON Feed</a>
        <a href="{rss_url}">RSS</a>
    </div>
</li>
"""


def generate_index_html(
    feeds_dir: Path,
    output_path: Path,
    title: Optional[str] = None,
    description: Optional[str] = None,
) -> None:
    """Generate an index.html page listing all feeds.

    Args:
        feeds_dir: Directory containing feed subdirectories
        output_path: Path to write index.html
        title: Site title (overrides config, defaults to "Feed Index")
        description: Site description (overrides config, defaults to generic description)
    """
    # Load site config (falls back to defaults)
    config = _load_site_config(feeds_dir)
    
    # CLI args override config file
    site_title = title or config.title
    site_description = description or config.description
    
    feed_items_html = []
    autodiscovery_links = []

    # Find all feed.json files
    for feed_json in sorted(feeds_dir.rglob("feed.json")):
        try:
            feed_data = _load_feed(feed_json)
            if not feed_data:
                continue

            # Calculate relative paths
            rel_dir = feed_json.parent.relative_to(feeds_dir)
            json_url = f"{rel_dir}/feed.json"
            rss_url = f"{rel_dir}/feed.xml"

            # Get feed info
            feed_title = feed_data.get("title", rel_dir.name)
            feed_desc = feed_data.get("description", "")
            items = feed_data.get("items", [])
            item_count = len(items)

            # Get last updated from most recent item
            last_updated = _get_last_updated(items)

            feed_items_html.append(FEED_ITEM_TEMPLATE.format(
                title=_escape_html(feed_title),
                description=_escape_html(feed_desc) if feed_desc else "No description",
                item_count=item_count,
                last_updated=last_updated,
                json_url=json_url,
                rss_url=rss_url,
            ))

            # Add autodiscovery link
            autodiscovery_links.append(
                f'<link rel="alternate" type="application/rss+xml" title="{_escape_html(feed_title)}" href="{rss_url}">'
            )

        except Exception as e:
            logger.warning(f"Error processing {feed_json}: {e}")

    # Generate HTML
    html = HTML_TEMPLATE.format(
        title=_escape_html(site_title),
        description=_escape_html(site_description),
        feed_items="".join(feed_items_html) if feed_items_html else "<li>No feeds found</li>",
        autodiscovery="\n    ".join(autodiscovery_links),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    logger.info(f"Generated index at {output_path}")


def _load_site_config(feeds_dir: Path) -> SiteConfig:
    """Load site configuration from feeds_dir/site.yaml.
    
    Falls back to defaults if file doesn't exist.
    
    Args:
        feeds_dir: Directory to look for site.yaml
        
    Returns:
        SiteConfig with loaded or default values
    """
    config_path = feeds_dir / "site.yaml"
    
    if not config_path.exists():
        logger.debug(f"No site.yaml found at {config_path}, using defaults")
        return SiteConfig()
    
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        
        logger.debug(f"Loaded site config from {config_path}")
        return SiteConfig(
            title=data.get("title", SiteConfig().title),
            description=data.get("description", SiteConfig().description),
        )
    except (yaml.YAMLError, IOError) as e:
        logger.warning(f"Failed to load site.yaml: {e}, using defaults")
        return SiteConfig()


def _load_feed(path: Path) -> Optional[dict]:
    """Load a feed.json file."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return None


def _get_last_updated(items: list[dict]) -> str:
    """Get the most recent date from items."""
    dates = []
    for item in items:
        date_str = item.get("date_published") or item.get("date_modified")
        if date_str:
            try:
                dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                # Convert to naive datetime for comparison (use UTC)
                if dt.tzinfo is not None:
                    dt = dt.replace(tzinfo=None)
                dates.append(dt)
            except (ValueError, AttributeError):
                pass

    if dates:
        return max(dates).strftime("%Y-%m-%d")
    return "Unknown"


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
